name: Jobs

on: [push]



jobs:
  basic-test:
    runs-on: ubuntu-latest
    steps:
      - name: Run start
        run: |
          sudo echo "ohohohohohohohohohohohoh"
      - uses: actions/checkout@v3
      - name: Run tests
        run: |
          qemu-system-riscv64 --version
          rustup target add riscv64gc-unknown-none-elf
          git config --global --add safe.directory /__w/rCore-Tutorial-Code-2023S/rCore-Tutorial-Code-2023S
          git clone https://github.com/LearningOS/rCore-Tutorial-Checker-2023S.git ci-user
          git clone https://github.com/LearningOS/rCore-Tutorial-Test-2023S.git ci-user/user
          ID=`git rev-parse --abbrev-ref HEAD | grep -oP 'ch\K[0-9]'`
          cd ci-user && make test CHAPTER=$ID passwd=${{ secrets.BASE_TEST_TOKEN }} > ../output.txt
          cat ../output.txt
      - name: end
        id: end
        run: |
          cat output.txt | grep -a "Test passed" | grep -oP "\d{1,}/\d{1,}" | xargs -i echo "points={}"
          cat output.txt | grep -a "Test passed" | grep -oP "\d{1,}/\d{1,}" | xargs -i echo "points={}" >> $GITHUB_OUTPUT
